### PR TITLE
Fix the strip pitch and minor updates

### PR DESCRIPTION
**Pull request by yeckang**
# Fix the strip pitch
* strip pitch on the tracking chambers is now 250.03 um.

# minor updates
* Track analyzer has updated with adjusted ranges of the plots.
* The recipe is updated.

### CODE REVIEW

**Comment by jshlee** [comment]
@pietverwilligen can u check this change

**Comment by jshlee** [comment]
@pietverwilligen are you happy with this change?

**Comment by yeckang** [comment]
I've updated the geometry for the 20x10 chambers with new mapping.

GE 1/1 chamber 4 eta partition 5 is assigned for the 20x10 chamber.
And its strip pitch is 400um.

The mapping is also corrected to get the proper position of the recHits.

**Comment by jshlee** [comment]
is everything ok to merge?

**Comment by yeckang** [comment]
At the moment, it is okay with the data. But the simulation is not working...

**Comment by jshlee** [comment]
yep, i assume some overlapping volumes appeared

**Comment by yeckang** [comment]
The issue with simulation is resolved.

**Comment by jshlee** [comment]
so merge?

**Comment by yeckang** [comment]
Yes. We can merge it.

**Comment by pietverwilligen** [comment]
+1

**Pull request merged**
