### PR TITLE
Change in the origin of the stand and scintillator

### PR DESCRIPTION
**Pull request by seulgi324**
Changed the origin of the stand to make the ground set to 0 and added one scintillator

### CODE REVIEW

**Comment by jshlee** [comment]
@seulgi324, dont u make changes to the xmls?

**Comment by yeckang** [comment]
> @seulgi324, dont u make changes to the xmls?

The XML files are not changed. But we need to add some XML files in Geoemtry cfi file to build geometry correctly.

**Comment by jshlee** [comment]
so this is ready to be merged?

**Comment by yeckang** [comment]
Yes, I expect we will see more hits from narrow eta paritions.

**Pull request merged**
